lorem_10ln = """Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores quasi quo voluptatem a excepturi facilis obcaecati saepe, impedit corporis provident quaerat? Ipsum autem dolorum adipisci sunt magnam esse necessitatibus ipsa.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores quasi quo voluptatem a excepturi facilis obcaecati saepe, impedit corporis provident quaerat? Ipsum autem dolorum adipisci sunt magnam esse necessitatibus ipsa.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores quasi quo voluptatem a excepturi facilis obcaecati saepe, impedit corporis provident quaerat? Ipsum autem dolorum adipisci sunt magnam esse necessitatibus ipsa.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores quasi quo voluptatem a excepturi facilis obcaecati saepe, impedit corporis provident quaerat? Ipsum autem dolorum adipisci sunt magnam esse necessitatibus ipsa.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores quasi quo voluptatem a excepturi facilis obcaecati saepe, impedit corporis provident quaerat? Ipsum autem dolorum adipisci sunt magnam esse necessitatibus ipsa.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores quasi quo voluptatem a excepturi facilis obcaecati saepe, impedit corporis provident quaerat? Ipsum autem dolorum adipisci sunt magnam esse necessitatibus ipsa.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores quasi quo voluptatem a excepturi facilis obcaecati saepe, impedit corporis provident quaerat? Ipsum autem dolorum adipisci sunt magnam esse necessitatibus ipsa.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores quasi quo voluptatem a excepturi facilis obcaecati saepe, impedit corporis provident quaerat? Ipsum autem dolorum adipisci sunt magnam esse necessitatibus ipsa.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores quasi quo voluptatem a excepturi facilis obcaecati saepe, impedit corporis provident quaerat? Ipsum autem dolorum adipisci sunt magnam esse necessitatibus ipsa.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores quasi quo voluptatem a excepturi facilis obcaecati saepe, impedit corporis provident quaerat? Ipsum autem dolorum adipisci sunt magnam esse necessitatibus ipsa."""
